name: acousti_care_frontend
description: "An app to detect diabetes."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  flutter_sound: ^9.2.13
  record: ^5.1.2
  just_audio: ^0.9.41
  path_provider: ^2.1.4
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.6
  cache_manager: ^1.0.0+4
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

