name: acousti_care_frontend
description: "An app to detect diabetes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.0
  record: ^4.4.4 
  just_audio: ^0.9.41
  path_provider: ^2.0.15
  provider: ^6.0.5 
  path: ^1.8.3
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.6
  cache_manager: ^1.0.0+4
  device_info_plus: ^4.0.0
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.69.2
  html: ^0.15.0
  path_provider_android: ^2.2.10
  url_launcher: ^6.0.13
  timezone: ^0.9.0
  flutter_local_notifications: ^12.0.4
  webfeed: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700